SELECT TOP (1000) [PaymentInvoiceId]
      ,[BookingId]
      ,[Amount]
      ,[PaymentDate]
      ,[PaymentMethod]
      ,[PaymentStatus]
      ,[InvoiceDate]
      ,[InvoiceNotes]
  FROM [Sun_Flower_Hotel].[dbo].[PaymentInvoices]
